### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by srepeat** [spartajet/javafx-boot-demo#1]
拉取下来无法使用，FXMLController出现错误  应该de这个依赖存在一定的问题

**Comment by spartajet** [comment]
这个好像需要翻墙的

**Comment by liurijin123** [comment]
怎么实现一个页面的跳转呢

**Comment by srepeat** [comment]
这个可以使用一个类，来管理页面路由去处理，这种方式就是借鉴前端的VUE路由管理




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "刘通"<notifications@github.com&gt;; 
发送时间: 2020年9月7日(星期一) 晚上8:57
收件人: "spartajet/javafx-boot-demo"<javafx-boot-demo@noreply.github.com&gt;; 
抄送: "鱼羊"<1546656922@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [spartajet/javafx-boot-demo] 问题反馈 (#1)





 
怎么实现一个页面的跳转呢

**Comment by spartajet** [comment]
跳转和传统方法一致，也可以自己写一个路由器

**Comment by srepeat** [comment]
对的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "spartajet"<notifications@github.com&gt;; 
发送时间: 2020年9月7日(星期一) 晚上9:23
收件人: "spartajet/javafx-boot-demo"<javafx-boot-demo@noreply.github.com&gt;; 
抄送: "鱼羊"<1546656922@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [spartajet/javafx-boot-demo] 问题反馈 (#1)





 
跳转和传统方法一致，也可以自己写一个路由器
